name: Build executables

on:
  push:
    branches: [main]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pyinstaller main.spec
      - uses: actions/upload-artifact@v4
        with:
          name: ejecutable-linux
          path: dist/trazador-cubico

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pyinstaller main.spec
      - uses: actions/upload-artifact@v4
        with:
          name: ejecutable-windows-final-proyecto
          path: dist/trazador-cubico.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pyinstaller main.spec
      - uses: actions/upload-artifact@v4
        with:
          name: ejecutable-macos
          path: dist/trazador-cubico